---

filesdir: "{{role_path}}/files"

dotfiles_base:
  ~/.bashrc:
    src: "{{filesdir}}/bashrc"
  ~/.bcrc:
    src: "{{filesdir}}/bcrc"

# xfce4-terminal doesn't like symlinked config and will replace the symlink
# with  regular file. Hard link it instead.
dotfiles_base_hl:
  ~/.config/xfce4/terminal/terminalrc:
    src: "{{filesdir}}/xfce4-terminalrc"
