---

filesdir: "{{role_path}}/files"

dotfiles_base:
  ~/.bashrc:
    src: "{{filesdir}}/bashrc"
  ~/.bcrc:
    src: "{{filesdir}}/bcrc"
  ~/.xmonad/xmonad.hs:
    src: "{{filesdir}}/xmonad.hs"
  ~/.xmonad/xmobarrc:
    src: "{{filesdir}}/xmobarrc"

# xfce4-terminal doesn't like symlinked config and will replace the symlink
# with  regular file. Hard link it instead.
#dotfiles_base_hl:
#  ~/.config/xfce4/terminal/terminalrc:
#    src: "{{filesdir}}/xfce4-terminalrc"
