---


- name: test existence of downloads dir
  stat: path=~/Downloads
  register: Downloads

- name: create dl symlink
  file: src=~/Downloads dest=~/dl state=link
  when: Downloads.stat.exists == True

- name: create ~/.xmonad dir
  file: path=~/.xmonad state=directory

- name: link some dotfiles
  file: path={{item.key}} state=link src={{item.value.src}}
  with_dict: "{{ dotfiles_base }}"

#- name: hard link some dotfiles
#  file: path={{item.key}} state=hard src={{item.value.src}}
#  with_dict: dotfiles_base_hl

# Leave vim alone for now
#- include: vim.yml
