# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export EDITOR=vim

# git aliases
alias ga='git add'
alias gc='git commit -v'
alias gca='git commit -av'
alias gcammm='git commit -av -m'.''
alias gd='git diff'
alias gp='git push'
alias gs='git status'
alias gu='git pull'

# check git status for directories in the pwd
alias gsdirs='for d in $(ls); do echo ==== $d; (cd $d; git status); done'

# Get current wx obs at UW ATG
alias uwatgwx='curl -s http://www.atmos.washington.edu/cgi-bin/latest_uw.cgi | awk '\''NR>8 && NR<14'\'''

# Set SSH_AUTH_SOCK to point to the most recently started ssh-agent process
alias reset-authsock='export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name 'agent*' -user $USER | head -n1)'

# For pymodoro
alias pomo='touch ~/.pomodoro_session'
alias pomoc='rm ~/.pomodoro_session'

alias bc="bc ~/.bcrc"
alias ll="ls -l"

# Various repos
alias notes="cd ~/gp/notes"

if [ -x /usr/bin/vagrant ]; then
  alias v="vagrant"
fi

## for virtualenvwrapper
if [ -x /usr/bin/virtualenvwrapper.sh ]; then
	export WORKON_HOME=~/virtualenvs
	if [ ! -d $WORKON_HOME ]; then
		mkdir $WORKON_HOME
	fi
	. /usr/bin/virtualenvwrapper.sh
fi

## Adapted from  https://unix.stackexchange.com/questions/101198/how-to-send-command-output-to-gnu-screens-copy-mode-buffer
## Using shred instead of rm
function screen_send_to_copy_mode() {
	tmp=$(mktemp) || exit
	cat > "$tmp" &&
		screen -X readbuf "$tmp"
	ret=$?
	(sleep 2; shred -u "$tmp")&
	exit "$ret"
}

## Call pass, remove newline, send to screen copybuffer
function spass() {
	pass $1 | tr -d '\n' | screen_send_to_copy_mode
}
## Get the same completion behavior when using spass
source  /usr/share/bash-completion/completions/pass
complete -o filenames -o nospace -F _pass spass

